adding plumed support + generic non-gmxapi version
delemottelab/string-method-gmxapi pull request #25
Opened 2021-05-03 10:35 UTC by milafternoon

Hi, please take your time to revise the changes & feel free to suggest changes. 

I'll add some extra docs soon to account for the additional options, but for now the existing functionalities should not be affected.

2021-05-06 18:20 UTC, sperezconesa requested changes

2021-05-06 18:20 UTC, sperezconesa commented on mdtools.py
> +    mpi_rank = mpi_rank - 1
I added this to make it work with one mpirank.
```suggestion
    mpi_rank = max(mpi_rank - 1,0)
```

2021-05-06 18:20 UTC, sperezconesa commented on mdtools.py
> +        mdrun_options_parse = mdrun_options
Not adding this generated a bug.
```suggestion
        mdrun_options_parse = mdrun_options[:]
```

2021-05-18 12:43 UTC, sperezconesa approved these changes

2021-05-18 12:44 UTC, sperezconesa commented
Looks good, I'll start testing ASAP and get back to you.

2021-05-18 13:24 UTC, milafternoon commented
Sure, here I'm finally running it with my system of interest, I'll
hopefully catch any issues should they come up! Also working on separating
the example into two distinct directories and adding a small section to
README.


wt., 18 maj 2021 o 14:45 Sergio Pérez Conesa ***@***.***>
napisał(a):

> Looks good, I'll start testing ASAP and get back to you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/delemottelab/string-method-gmxapi/pull/25#issuecomment-843139404>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF5WUYJGJD5FXLSKQQABPM3TOJONLANCNFSM44ASO5MQ>
> .
>

2021-05-18 16:32 UTC, sperezconesa commented
How did you run the simulations with gmx_mpi and no gmxapi? I'm having trouble doing that. What command did you add to `slurm.sh` and what did you modify in `mdtools.py`?

2021-05-18 19:04 UTC, milafternoon commented
Hi, I tried to clarify that in a follow-up mail - I did not in fact manage
to do that, at some point I mixed up two versions and it was gmx that
worked all the time, not gmx_mpi.



El dt., 18 de maig 2021, 18:32, Sergio Pérez Conesa <
***@***.***> va escriure:

> How did you run the simulations with gmx_mpi and no gmxapi? I'm having
> trouble doing that. What command did you add to slurm.sh and what did you
> modify in mdtools.py?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/delemottelab/string-method-gmxapi/pull/25#issuecomment-843328816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AF5WUYLWZ752OPPPSHWHET3TOKJBJANCNFSM44ASO5MQ>
> .
>

2021-05-31 17:48 UTC, sperezconesa approved these changes

2021-06-03 13:23 UTC, sperezconesa reviewed
![image](https://user-images.githubusercontent.com/27727343/120651795-6f2c5880-c47f-11eb-91a5-2495a14d2849.png)
This gives me a syntax error. I don't understand why. I'm using python 3.8.5

2021-06-03 20:35 UTC, milafternoon commented
Sorry, should be fixed now, I accidentally wrote "line in ..." instead of "line for line in..." while splitting an unreadable one-liner into two list comprehensions.

2021-06-08 16:09 UTC, sperezconesa reviewed
These changes had to be done for it to work on my cluster.

2021-06-08 16:09 UTC, sperezconesa commented on mdtools.py
> +        gmx = "mpiexec -n 1 gmx_mpi" if gmx_executable == "gmx_mpi" else "gmx"
So, mpiexec in my cluster needs to be srun... maybe there should be an input variable for this in config.json

2021-06-08 16:09 UTC, sperezconesa commented on mdtools.py
> +    proc_per_core = int(os.environ["SLURM_CPUS_ON_NODE"]) if "SLURM_CPUS_ON_NODE" in os.environ.keys() else 1
This should be SLURM_NTASKS_PER_NODE which is equal to the number of mpi tasks you can do in the node. The current variable is equal to the number of threads in the node, which in your case is equal to the number of mpitasks.

2021-06-08 16:09 UTC, sperezconesa commented on mdtools.py
> +def _grompp(args: dict):
args.update({'gmx_executable': 'gmx_mpi'}) in my system returns None and does the update to args. Maybe this has changed from python version (I'm using 3.8.5).
I suggest:
```python
def _grompp(args: dict):
    args.update({"gmx_executable": "gmx_mpi"})
    return grompp(**args)
```

2021-06-22 17:09 UTC, sperezconesa reviewed
Sorry I didn't talk about this with you. I am using black -l 79 for formatting. But I don't have any strong opinions so we can use something else if you want.

2021-06-23 07:15 UTC, merged

2021-06-23 07:15 UTC, sperezconesa commented
I have decide to make a dev branch in the main repo so me and Milosz can work more efficiently.